spring:
  application:
    name: RestfullJPATAsks

  datasource:
    url: jdbc:postgresql://localhost:5432/JPATasks
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  logging:
    level:
      org.springframework: DEBUG



